#!/usr/bin/env php
<?php

use Wex\App;

error_reporting(E_ALL);
ini_set('display_errors', 1);

define('__ROOT__', realpath(__DIR__));
require __ROOT__ . '/vendor/autoload.php';

$command    = $_SERVER['argv'][1];
$parameters = array_slice($_SERVER['argv'], 2);

call_user_func('Wex\App::command', $command, $parameters);